name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose


  announce:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Send image
        run: cargo run -- pixelflut.uwu.industries:1234 0x0 347x219 img src/test/announcement.png # not --release cause im gangsta